# Generated by Django 4.2.5 on 2023-09-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("museum_api", "0004_article"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="id",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="article",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
