# Generated by Django 4.2.1 on 2023-06-04 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("museum_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exhibit",
            name="date_arrived",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="exhibit",
            name="responsible",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="gallery",
            name="area",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="gallery",
            name="floor",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="gallery",
            name="number",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Employee",
        ),
    ]
