# Generated by Django 4.2.1 on 2023-06-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("museum_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="exhibit",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="position",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
