# Generated by Django 4.2.1 on 2023-06-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "museum_api",
            "0002_alter_employee_id_alter_exhibit_id_alter_gallery_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="arttype",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
