name: Building docker images

on: push

jobs:
  matrix_prep:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        uses: JoshuaTheMiller/conditional-build-matrix@main
        with:
          filter: "[]"
  build:
    needs: matrix_prep
    strategy:
      matrix: ${{ fromJson(needs.matrix_prep.outputs.matrix) }}
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nelonoel/branch-name@v1.0.1
      - name: Caching Docker builds
        uses: actions/cache@v3.2.5
        with:
          path: ~/docker-cache
          key: ${{ runner.os }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: "./${{ matrix.path }}"
          file: "./${{ matrix.path }}/Dockerfile"
          push: ${{ env.BRANCH_NAME == 'master' }}
          tags: ${{ matrix.tag }},${{ matrix.tag }}:${{ matrix.version }}
          cache-to: ~/docker-cache
          cache-from: ~/docker-cache
